apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: energy-dashboard
  name: database
spec:
  instances: 1
  replicationSlots:
    highAvailability:
      enabled: true
  affinity:
    topologyKey: topology.kubernetes.io/zone
  backup:
    volumeSnapshot:
       online: true
       onlineConfiguration:
         immediateCheckpoint: true
  storage:
    size: 16Gi
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 128Mi
  postgresql:
    parameters:
      shared_buffers: "32MB"
