apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: energy-dashboard
  name: database
spec:
  instances: 2
  replicationSlots:
    highAvailability:
      enabled: true
  affinity:
    topologyKey: topology.kubernetes.io/zone
  storage:
    size: 16Gi
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 256Mi
