apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: energy-dashboard
  name: database
spec:
  instances: 2
  replicationSlots:
    highAvailability:
      enabled: true
  affinity:
    topologyKey: topology.kubernetes.io/zone
  storage:
    size: 16Gi
