apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: energy-dashboard
  name: lookingforgrowth-energy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-lfg-staging
spec:
  ingressClassName: nginx-lfg
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  rules:
  - host: energy.lookingforgrowth.uk
    http:
      paths:
      - pathType: Prefix
        path: /api/
        backend:
          service:
            name: backend
            port:
              number: 80
  - host: energy.lfgdata.uk
    http:
      paths:
      - pathType: Prefix
        path: /api/
        backend:
          service:
            name: backend
            port:
              number: 80
  tls:
  - hosts:
    - energy.lookingforgrowth.uk
    - energy.lfgdata.uk
    secretName: lookingforgrowth-energy-tls
