apiVersion: v1
kind: Service
metadata:
  namespace: energy-dashboard
  name: acme-solver
spec:
  type: NodePort
  selector:
    app: ingress-migration
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
